include: ../analysis_options.yaml

analyzer:
  exclude:
    - test/*.mocks.dart
    - example/**/*.dart # Todo(pavanpodila) remove this after mobx_codegen is migrated to null-safety
  strong-mode:
    implicit-casts: false
