[build]
  command = "echo 'Deploying redirect to mobx.vyuh.tech'"
  publish = "tool/netlify-redirect"

[[redirects]]
  from = "/*"
  to = "https://mobx.vyuh.tech/:splat"
  status = 301
  force = true
