// Mocks generated by Mockito 5.0.0 from annotations
// in mobx/test/all_tests.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;

import 'shared_mocks.dart' as _i2;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [MockContext].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockContext extends _i1.Mock implements _i2.MockContext {
  MockMockContext() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MockActionController].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockActionController extends _i1.Mock
    implements _i2.MockActionController {
  MockMockActionController() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MockAtom].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockAtom extends _i1.Mock implements _i2.MockAtom {
  MockMockAtom() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [MockDerivation].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockDerivation extends _i1.Mock implements _i2.MockDerivation {
  MockMockDerivation() {
    _i1.throwOnMissingStub(this);
  }
}
