name: Dart CI

on: [push]

jobs:
  build_dart_packages:
    runs-on: ubuntu-latest

    container:
      image: google/dart:${{ matrix.version }}

    strategy:
      matrix:
        package: ["mobx", "mobx_codegen"]
        version: ["latest", "dev"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: |
          pub get
      - name: Run Analyzer
        working-directory: ${{ matrix.package }}
        run: |
          dartanalyzer --fatal-infos --fatal-warnings .
      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: |
          pub run test_coverage
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info

  build_flutter_packages:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        package: ["flutter_mobx"]
        channel: ["stable", "beta"]

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: subosito/flutter-action@v1
        with:
          channel: ${{ matrix.channel }}
      - run: flutter --version
      - run: cd ${{ matrix.package }} && flutter packages get
      - run: cd ${{ matrix.package }} && flutter analyze
      - run: cd ${{ matrix.package }} && flutter test --coverage --coverage-path coverage/lcov.info
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info
