name: Dart CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  google/dart:latest

    strategy:
      matrix:
        package: ['mobx', 'mobx_codegen']

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies for ${{ matrix.package }}
      run: |
        cd ${{ matrix.package }}
        pub get
    - name: Run tests for ${{ matrix.package }}
      run: |
        cd ${{ matrix.package }}
        pub run test
