# Mirror master to main branches in the mobx.dart repository.
on:
  push:
    branches:
      - 'main'

# Declare default permissions as read only.
permissions: read-all

jobs:
  mirror_job:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'mobxjs/mobx.dart' }}
    name: Mirror main branch to master branch
    steps:
      - name: Mirror action step
        id: mirror
        uses: google/mirror-branch-action@30c52ee21f5d3bd7fb28b95501c11aae7f17eebb # v2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          source: 'main'
          dest: 'master'